namespace: paperdebugger-dev
openai_base_url: https://api.openai.com/v1
openai_api_key: sk-dummy-OPENAI_API_KEY
inference_base_url: https://inference.paperdebugger.workers.dev
inference_api_key: sk-dummy-OPEN-ROUTER
jwt_signing_key: paperdebugger
ghcr_docker_config: dummy-ghcr-docker-config
cloudflare_tunnel_token: dummy-cloudflare-tunnel-token

paperdebugger:
  image: ghcr.io/paperdebugger/sharelatex-paperdebugger:latest

paperdebuggerMcpServer:
  image: ghcr.io/paperdebugger/paperdebugger-mcp-server:main-14409c5

paperdebuggerXtraMcpServer:
  image: ghcr.io/paperdebugger/xtragpt-mcp-server:sha-2f1404c

mongo:
  in_cluster: true
  uri: "" # if in_cluster is false, use the external mongo instead
  image: mongo:latest
