name: build backend for prd
on:
  push:
    tags:
      - 'v*'
  repository_dispatch:
    types: [prd]

jobs:
  build-backend-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      IMAGE_TAG: ${{ steps.output.outputs.IMAGE_TAG }}
      PAPERDEBUGGER_IMAGE: ${{ steps.output.outputs.PAPERDEBUGGER_IMAGE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup env
        run: |
          echo "MONOREPO_REVISION=$(git rev-parse HEAD | cut -c1-6)" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.event.client_payload.tag }}" >> $GITHUB_ENV
          echo "VERSION=${{ github.event.client_payload.tag }}" >> $GITHUB_ENV
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        run: |
          make all
      - id: output
        name: Output image tag
        run: |
          export IMAGE_TAG=${BRANCH_NAME}-${MONOREPO_REVISION}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "PAPERDEBUGGER_IMAGE=ghcr.io/paperdebugger/sharelatex-paperdebugger:${IMAGE_TAG}" >> $GITHUB_OUTPUT

  deploy-backend:
    needs: build-backend-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Clone deploy repo
        run: |
          git clone https://${{ secrets.GH_PAT }}@github.com/paperdebugger/deploy.git ../deploy
      - name: Generate kubernetes manifests
        env:
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL_PRD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_PRD }}
          INFERENCE_BASE_URL: ${{ secrets.INFERENCE_BASE_URL_PRD }}
          INFERENCE_API_KEY: ${{ secrets.INFERENCE_API_KEY_PRD }}
          MCP_BASIC_KEY: ${{ secrets.MCP_BASIC_KEY_PRD }}
          MCP_PAPERSCORE_KEY: ${{ secrets.MCP_PAPERSCORE_KEY_PRD }}
          XTRAMCP_OPENAI_BASE_URL: ${{ secrets.XTRAMCP_OPENAI_BASE_URL_PRD }}
          XTRAMCP_OPENAI_API_KEY: ${{ secrets.XTRAMCP_OPENAI_API_KEY_PRD }}
          XTRAMCP_OPENREVIEW_BASE_URL: ${{ secrets.XTRAMCP_OPENREVIEW_BASE_URL_PRD }}
          XTRAMCP_OPENREVIEW_USERNAME: ${{ secrets.XTRAMCP_OPENREVIEW_USERNAME_PRD }}
          XTRAMCP_OPENREVIEW_PASSWORD: ${{ secrets.XTRAMCP_OPENREVIEW_PASSWORD_PRD }}
          XTRAMCP_CROSSREF_EMAIL_ADDRESS: ${{ secrets.XTRAMCP_CROSSREF_EMAIL_ADDRESS_PRD }}
          XTRAMCP_DOI_EMAIL_ADDRESS: ${{ secrets.XTRAMCP_DOI_EMAIL_ADDRESS_PRD }}
          XTRAMCP_ARXIV_METADATA_DB_URL: ${{ secrets.XTRAMCP_ARXIV_METADATA_DB_URL_PRD }}
          XTRAMCP_MONGO_URI: ${{ secrets.XTRAMCP_MONGO_URI_PRD }}
          MONGO_URI: ${{ secrets.MONGO_URI_PRD }}
          GHCR_DOCKER_CONFIG: ${{ secrets.GHCR_DOCKER_CONFIG_PRD }}
          CLOUDFLARE_TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN_PRD }}
        run: |
          export PAPERDEBUGGER_IMAGE=${{ needs.build-backend-and-push.outputs.PAPERDEBUGGER_IMAGE }}
          mkdir -p ../deploy/prd
          ./hack/prd.sh > ../deploy/prd/paperdebugger.yaml
      - name: Push changes to deploy repo
        run: |
          export IMAGE_TAG=${{ needs.build-backend-and-push.outputs.IMAGE_TAG }}
          cd ../deploy
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add prd/paperdebugger.yaml
          git diff --staged --quiet || git commit -m "chore: update paperdebugger prd, revision ${IMAGE_TAG}"
          git push
